import * as Rx from 'rxjs'
import {takeUntil,finalize} from 'rxjs/operators'

const interval = Rx.interval(200)
const fetchingData = Rx.timer(4000) // a mock for fetching data which takes 4 secs

interval.pipe(
    takeUntil(fetchingData),
    finalize(() => console.log('Data has been fetched!'))
).subscribe(i => console.log('.'.repeat(i+1)))

/*
    .
    ..
    ...
    ....
    .....
    ......
    .......
    ........
    .........
    ..........
    ...........
    ............
    .............
    ..............
    ...............
    ................
    .................
    ..................
    ...................
    Data has been fetched!
*/